services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB_URL=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB_URL=db
    networks:
      - spring-postgres
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
networks:
  spring-postgres:
